trigger:
- master

jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
          python.architecture: x64
          TOXENV: py27
      maxParallel: 4

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade tox
        displayName: install tox
      - script: tox
        displayName: run tox

  - job: 'Publish'
    dependsOn: 'Test'
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          architecture: 'x64'

      - script: python setup.py sdist bdist_wheel
        displayName: 'Build sdist & wheel'
